//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoLive.NFe.SOAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfe.sefaz.am.gov.br/services2/services/NfeStatusServico2?wsdl")]
        public string am_hom_statusServico {
            get {
                return ((string)(this["am_hom_statusServico"]));
            }
            set {
                this["am_hom_statusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/NfeStatusServico/NfeStatusServico.asmx")]
        public string ba_hom_StatusServico {
            get {
                return ((string)(this["ba_hom_StatusServico"]));
            }
            set {
                this["ba_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeStatusServico2?wsdl")]
        public string ce_hom_StatusServico {
            get {
                return ((string)(this["ce_hom_StatusServico"]));
            }
            set {
                this["ce_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeStatusServico2?wsdl")]
        public string go_hom_StatusServico {
            get {
                return ((string)(this["go_hom_StatusServico"]));
            }
            set {
                this["go_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeStatusServico2?wsdl")]
        public string mg_hom_StatusServico {
            get {
                return ((string)(this["mg_hom_StatusServico"]));
            }
            set {
                this["mg_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2?wsdl")]
        public string ms_hom_StatusServico {
            get {
                return ((string)(this["ms_hom_StatusServico"]));
            }
            set {
                this["ms_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3?wsdl")]
        public string pr_hom_StatusServico {
            get {
                return ((string)(this["pr_hom_StatusServico"]));
            }
            set {
                this["pr_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asm" +
            "x")]
        public string rs_hom_StatusServico {
            get {
                return ((string)(this["rs_hom_StatusServico"]));
            }
            set {
                this["rs_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico2.asmx")]
        public string sp_hom_StatusServico {
            get {
                return ((string)(this["sp_hom_StatusServico"]));
            }
            set {
                this["sp_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string svan_hom_StatusServico {
            get {
                return ((string)(this["svan_hom_StatusServico"]));
            }
            set {
                this["svan_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeStatusServico/NfeStatusServi" +
            "co2.asmx")]
        public string svrs_hom_StatusServico {
            get {
                return ((string)(this["svrs_hom_StatusServico"]));
            }
            set {
                this["svrs_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfe.sefaz.am.gov.br/services2/services/NfeAutorizacao?wsdl")]
        public string am_hom_NFeAutorizacao {
            get {
                return ((string)(this["am_hom_NFeAutorizacao"]));
            }
            set {
                this["am_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string ba_hom_NFeAutorizacao {
            get {
                return ((string)(this["ba_hom_NFeAutorizacao"]));
            }
            set {
                this["ba_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeAutorizacao?wsdl")]
        public string ce_hom_NFeAutorizacao {
            get {
                return ((string)(this["ce_hom_NFeAutorizacao"]));
            }
            set {
                this["ce_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeAutorizacao?wsdl")]
        public string go_hom_NFeAutorizacao {
            get {
                return ((string)(this["go_hom_NFeAutorizacao"]));
            }
            set {
                this["go_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeAutorizacao?wsdl")]
        public string mg_hom_NFeAutorizacao {
            get {
                return ((string)(this["mg_hom_NFeAutorizacao"]));
            }
            set {
                this["mg_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeAutorizacao?wsdl")]
        public string ms_hom_NFeAutorizacao {
            get {
                return ((string)(this["ms_hom_NFeAutorizacao"]));
            }
            set {
                this["ms_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao?wsdl")]
        public string mt_hom_NFeAutorizacao {
            get {
                return ((string)(this["mt_hom_NFeAutorizacao"]));
            }
            set {
                this["mt_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeAutorizacao?wsdl")]
        public string pe_hom_NFeAutorizacao {
            get {
                return ((string)(this["pe_hom_NFeAutorizacao"]));
            }
            set {
                this["pe_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3?wsdl")]
        public string pr_hom_NFeAutorizacao {
            get {
                return ((string)(this["pr_hom_NFeAutorizacao"]));
            }
            set {
                this["pr_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string rs_hom_NFeAutorizacao {
            get {
                return ((string)(this["rs_hom_NFeAutorizacao"]));
            }
            set {
                this["rs_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx")]
        public string sp_hom_NFeAutorizacao {
            get {
                return ((string)(this["sp_hom_NFeAutorizacao"]));
            }
            set {
                this["sp_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string svan_hom_NFeAutorizacao {
            get {
                return ((string)(this["svan_hom_NFeAutorizacao"]));
            }
            set {
                this["svan_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.a" +
            "smx")]
        public string svrs_hom_NFeAutorizacao {
            get {
                return ((string)(this["svrs_hom_NFeAutorizacao"]));
            }
            set {
                this["svrs_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeRetAutorizacao?wsdl")]
        public string ce_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["ce_hom_NFeRetAutorizacao"]));
            }
            set {
                this["ce_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeRetAutorizacao?wsdl")]
        public string go_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["go_hom_NFeRetAutorizacao"]));
            }
            set {
                this["go_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRetAutorizacao?wsdl")]
        public string mg_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["mg_hom_NFeRetAutorizacao"]));
            }
            set {
                this["mg_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeRetAutorizacao?wsdl")]
        public string ms_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["ms_hom_NFeRetAutorizacao"]));
            }
            set {
                this["ms_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao?wsdl")]
        public string mt_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["mt_hom_NFeRetAutorizacao"]));
            }
            set {
                this["mt_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeRetAutorizacao?wsdl")]
        public string pe_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["pe_hom_NFeRetAutorizacao"]));
            }
            set {
                this["pe_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeStatusServico2?wsdl")]
        public string pe_hom_StatusServico {
            get {
                return ((string)(this["pe_hom_StatusServico"]));
            }
            set {
                this["pe_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/NfeRetAutorizacao/NfeRetAutorizacao.asmx" +
            "")]
        public string am_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["am_hom_NFeRetAutorizacao"]));
            }
            set {
                this["am_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRetAutorizacao3?wsdl")]
        public string pr_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["pr_hom_NFeRetAutorizacao"]));
            }
            set {
                this["pr_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.as" +
            "mx")]
        public string rs_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["rs_hom_NFeRetAutorizacao"]));
            }
            set {
                this["rs_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx")]
        public string sp_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["sp_hom_NFeRetAutorizacao"]));
            }
            set {
                this["sp_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string svan_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["svan_hom_NFeRetAutorizacao"]));
            }
            set {
                this["svan_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutoriz" +
            "acao.asmx")]
        public string svrs_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["svrs_hom_NFeRetAutorizacao"]));
            }
            set {
                this["svrs_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfe.sefaz.am.gov.br/services2/services/NfeConsulta2?wsdl")]
        public string am_hom_ConsultaProtocolo {
            get {
                return ((string)(this["am_hom_ConsultaProtocolo"]));
            }
            set {
                this["am_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx")]
        public string ba_hom_ConsultaProtocolo {
            get {
                return ((string)(this["ba_hom_ConsultaProtocolo"]));
            }
            set {
                this["ba_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeConsulta2?wsdl")]
        public string ce_hom_ConsultaProtocolo {
            get {
                return ((string)(this["ce_hom_ConsultaProtocolo"]));
            }
            set {
                this["ce_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeConsulta2?wsdl")]
        public string go_hom_ConsultaProtocolo {
            get {
                return ((string)(this["go_hom_ConsultaProtocolo"]));
            }
            set {
                this["go_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2?wsdl")]
        public string mg_hom_ConsultaProtocolo {
            get {
                return ((string)(this["mg_hom_ConsultaProtocolo"]));
            }
            set {
                this["mg_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeConsulta2?wsdl")]
        public string ms_hom_ConsultaProtocolo {
            get {
                return ((string)(this["ms_hom_ConsultaProtocolo"]));
            }
            set {
                this["ms_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl")]
        public string mt_hom_ConsultaProtocolo {
            get {
                return ((string)(this["mt_hom_ConsultaProtocolo"]));
            }
            set {
                this["mt_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2")]
        public string pe_hom_ConsultaProtocolo {
            get {
                return ((string)(this["pe_hom_ConsultaProtocolo"]));
            }
            set {
                this["pe_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeConsulta3?wsdl")]
        public string pr_hom_ConsultaProtocolo {
            get {
                return ((string)(this["pr_hom_ConsultaProtocolo"]));
            }
            set {
                this["pr_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string rs_hom_ConsultaProtocolo {
            get {
                return ((string)(this["rs_hom_ConsultaProtocolo"]));
            }
            set {
                this["rs_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsulta2.asmx")]
        public string sp_hom_ConsultaProtocolo {
            get {
                return ((string)(this["sp_hom_ConsultaProtocolo"]));
            }
            set {
                this["sp_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string svan_hom_ConsultaProtocolo {
            get {
                return ((string)(this["svan_hom_ConsultaProtocolo"]));
            }
            set {
                this["svan_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string svrs_hom_ConsultaProtocolo {
            get {
                return ((string)(this["svrs_hom_ConsultaProtocolo"]));
            }
            set {
                this["svrs_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfe.sefaz.am.gov.br/services2/services/NfeInutilizacao2?wsdl")]
        public string am_hom_NFeInutilizacao {
            get {
                return ((string)(this["am_hom_NFeInutilizacao"]));
            }
            set {
                this["am_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeInutilizacao2?wsdl")]
        public string ce_hom_NFeInutilizacao {
            get {
                return ((string)(this["ce_hom_NFeInutilizacao"]));
            }
            set {
                this["ce_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeInutilizacao2?wsdl")]
        public string go_hom_NFeInutilizacao {
            get {
                return ((string)(this["go_hom_NFeInutilizacao"]));
            }
            set {
                this["go_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2?wsdl")]
        public string mg_hom_NFeInutilizacao {
            get {
                return ((string)(this["mg_hom_NFeInutilizacao"]));
            }
            set {
                this["mg_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeInutilizacao2?wsdl")]
        public string ms_hom_NFeInutilizacao {
            get {
                return ((string)(this["ms_hom_NFeInutilizacao"]));
            }
            set {
                this["ms_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl")]
        public string mt_hom_NFeInutilizacao {
            get {
                return ((string)(this["mt_hom_NFeInutilizacao"]));
            }
            set {
                this["mt_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeInutilizacao2?wsdl")]
        public string pe_hom_NFeInutilizacao {
            get {
                return ((string)(this["pe_hom_NFeInutilizacao"]));
            }
            set {
                this["pe_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeInutilizacao3?wsdl")]
        public string pr_hom_NFeInutilizacao {
            get {
                return ((string)(this["pr_hom_NFeInutilizacao"]));
            }
            set {
                this["pr_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string rs_hom_NFeInutilizacao {
            get {
                return ((string)(this["rs_hom_NFeInutilizacao"]));
            }
            set {
                this["rs_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx")]
        public string sp_hom_NFeInutilizacao {
            get {
                return ((string)(this["sp_hom_NFeInutilizacao"]));
            }
            set {
                this["sp_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx")]
        public string svan_hom_NFeInutilizacao {
            get {
                return ((string)(this["svan_hom_NFeInutilizacao"]));
            }
            set {
                this["svan_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao" +
            "2.asmx")]
        public string svrs_hom_NFeInutilizacao {
            get {
                return ((string)(this["svrs_hom_NFeInutilizacao"]));
            }
            set {
                this["svrs_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfe.sefaz.am.gov.br/services2/services/RecepcaoEvento?wsdl")]
        public string am_hom_RecepcaoEvento {
            get {
                return ((string)(this["am_hom_RecepcaoEvento"]));
            }
            set {
                this["am_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/sre/recepcaoevento.asmx")]
        public string ba_hom_RecepcaoEvento {
            get {
                return ((string)(this["ba_hom_RecepcaoEvento"]));
            }
            set {
                this["ba_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/RecepcaoEvento?wsdl")]
        public string ce_hom_RecepcaoEvento {
            get {
                return ((string)(this["ce_hom_RecepcaoEvento"]));
            }
            set {
                this["ce_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/RecepcaoEvento?wsdl")]
        public string go_hom_RecepcaoEvento {
            get {
                return ((string)(this["go_hom_RecepcaoEvento"]));
            }
            set {
                this["go_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento?wsdl")]
        public string mg_hom_RecepcaoEvento {
            get {
                return ((string)(this["mg_hom_RecepcaoEvento"]));
            }
            set {
                this["mg_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/RecepcaoEvento?wsdl")]
        public string ms_hom_RecepcaoEvento {
            get {
                return ((string)(this["ms_hom_RecepcaoEvento"]));
            }
            set {
                this["ms_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl")]
        public string mt_hom_RecepcaoEvento {
            get {
                return ((string)(this["mt_hom_RecepcaoEvento"]));
            }
            set {
                this["mt_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/RecepcaoEvento?wsdl")]
        public string pe_hom_RecepcaoEvento {
            get {
                return ((string)(this["pe_hom_RecepcaoEvento"]));
            }
            set {
                this["pe_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRecepcaoEvento?wsdl")]
        public string pr_hom_RecepcaoEvento {
            get {
                return ((string)(this["pr_hom_RecepcaoEvento"]));
            }
            set {
                this["pr_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefaz.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string rs_hom_RecepcaoEvento {
            get {
                return ((string)(this["rs_hom_RecepcaoEvento"]));
            }
            set {
                this["rs_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        public string sp_hom_RecepcaoEvento {
            get {
                return ((string)(this["sp_hom_RecepcaoEvento"]));
            }
            set {
                this["sp_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string svan_hom_RecepcaoEvento {
            get {
                return ((string)(this["svan_hom_RecepcaoEvento"]));
            }
            set {
                this["svan_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/NfeInutilizacao/NfeInutilizacao.asmx")]
        public string ba_hom_NFeInutilizacao {
            get {
                return ((string)(this["ba_hom_NFeInutilizacao"]));
            }
            set {
                this["ba_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/NfeRetAutorizacao/NfeRetAutorizacao.asmx" +
            "")]
        public string ba_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["ba_hom_NFeRetAutorizacao"]));
            }
            set {
                this["ba_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl")]
        public string mt_hom_StatusServico {
            get {
                return ((string)(this["mt_hom_StatusServico"]));
            }
            set {
                this["mt_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.sefazvirtual.rs.gov.br/ws/recepcaoevento/recepcaoevento.a" +
            "smx")]
        public string svrs_hom_RecepcaoEvento {
            get {
                return ((string)(this["svrs_hom_RecepcaoEvento"]));
            }
            set {
                this["svrs_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homnfe.sefaz.am.gov.br/services2/services/cadconsultacadastro2?wsdl")]
        public string am_hom_ConsultaCadastro {
            get {
                return ((string)(this["am_hom_ConsultaCadastro"]));
            }
            set {
                this["am_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx")]
        public string ba_hom_ConsultaCadastro {
            get {
                return ((string)(this["ba_hom_ConsultaCadastro"]));
            }
            set {
                this["ba_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfeh.sefaz.ce.gov.br/nfe2/services/CadConsultaCadastro2?wsdl")]
        public string ce_hom_ConsultaCadastro {
            get {
                return ((string)(this["ce_hom_ConsultaCadastro"]));
            }
            set {
                this["ce_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homolog.sefaz.go.gov.br/nfe/services/v2/CadConsultaCadastro2?wsdl")]
        public string go_hom_ConsultaCadastro {
            get {
                return ((string)(this["go_hom_ConsultaCadastro"]));
            }
            set {
                this["go_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hnfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2?wsdl")]
        public string mg_hom_ConsultaCadastro {
            get {
                return ((string)(this["mg_hom_ConsultaCadastro"]));
            }
            set {
                this["mg_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sistemas.sefaz.ma.gov.br/wscadastro/CadConsultaCadastro2?wsdl")]
        public string ma_hom_ConsultaCadastro {
            get {
                return ((string)(this["ma_hom_ConsultaCadastro"]));
            }
            set {
                this["ma_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.ms.gov.br/homologacao/services2/CadConsultaCadastro2?wsdl" +
            "")]
        public string ms_hom_ConsultaCadastro {
            get {
                return ((string)(this["ms_hom_ConsultaCadastro"]));
            }
            set {
                this["ms_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro2?wsdl")]
        public string mt_hom_ConsultaCadastro {
            get {
                return ((string)(this["mt_hom_ConsultaCadastro"]));
            }
            set {
                this["mt_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/CadConsultaCadastro2?wsdl")]
        public string pr_hom_ConsultaCadastro {
            get {
                return ((string)(this["pr_hom_ConsultaCadastro"]));
            }
            set {
                this["pr_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cad.sefazrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx")]
        public string rs_hom_ConsultaCadastro {
            get {
                return ((string)(this["rs_hom_ConsultaCadastro"]));
            }
            set {
                this["rs_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro2.asmx")]
        public string sp_hom_ConsultaCadastro {
            get {
                return ((string)(this["sp_hom_ConsultaCadastro"]));
            }
            set {
                this["sp_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx")]
        public string svrs_hom_ConsultaCadastro {
            get {
                return ((string)(this["svrs_hom_ConsultaCadastro"]));
            }
            set {
                this["svrs_hom_ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/NfeDownloadNF/NfeDownloadNF.asmx")]
        public string an_hom_DownloadNFe {
            get {
                return ((string)(this["an_hom_DownloadNFe"]));
            }
            set {
                this["an_hom_DownloadNFe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx")]
        public string svcan_hom_RecepcaoEvento {
            get {
                return ((string)(this["svcan_hom_RecepcaoEvento"]));
            }
            set {
                this["svcan_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx")]
        public string svcan_hom_ConsultaProtocolo {
            get {
                return ((string)(this["svcan_hom_ConsultaProtocolo"]));
            }
            set {
                this["svcan_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string svcan_hom_StatusServico {
            get {
                return ((string)(this["svcan_hom_StatusServico"]));
            }
            set {
                this["svcan_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx")]
        public string svcan_hom_NFeAutorizacao {
            get {
                return ((string)(this["svcan_hom_NFeAutorizacao"]));
            }
            set {
                this["svcan_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx")]
        public string svcan_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["svcan_hom_NFeRetAutorizacao"]));
            }
            set {
                this["svcan_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx")]
        public string svcrs_hom_RecepcaoEvento {
            get {
                return ((string)(this["svcrs_hom_RecepcaoEvento"]));
            }
            set {
                this["svcrs_hom_RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx")]
        public string svcrs_hom_NFeInutilizacao {
            get {
                return ((string)(this["svcrs_hom_NFeInutilizacao"]));
            }
            set {
                this["svcrs_hom_NFeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx")]
        public string svcrs_hom_ConsultaProtocolo {
            get {
                return ((string)(this["svcrs_hom_ConsultaProtocolo"]));
            }
            set {
                this["svcrs_hom_ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx" +
            "")]
        public string svcrs_hom_StatusServico {
            get {
                return ((string)(this["svcrs_hom_StatusServico"]));
            }
            set {
                this["svcrs_hom_StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx")]
        public string svcrs_hom_NFeAutorizacao {
            get {
                return ((string)(this["svcrs_hom_NFeAutorizacao"]));
            }
            set {
                this["svcrs_hom_NFeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asm" +
            "x")]
        public string svcrs_hom_NFeRetAutorizacao {
            get {
                return ((string)(this["svcrs_hom_NFeRetAutorizacao"]));
            }
            set {
                this["svcrs_hom_NFeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfeautorizacao.asmx ")]
        public string sp_hom_NFCeAutorizacao {
            get {
                return ((string)(this["sp_hom_NFCeAutorizacao"]));
            }
            set {
                this["sp_hom_NFCeAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.sp.gov.br/ws/nferetautorizacao.asmx ")]
        public string sp_hom_NFCeRetAutorizacao {
            get {
                return ((string)(this["sp_hom_NFCeRetAutorizacao"]));
            }
            set {
                this["sp_hom_NFCeRetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx ")]
        public string sp_hom_NFCeInutilizacao {
            get {
                return ((string)(this["sp_hom_NFCeInutilizacao"]));
            }
            set {
                this["sp_hom_NFCeInutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.sp.gov.br/ws/nfeconsulta2.asmx ")]
        public string sp_hom_NFCeConsulta {
            get {
                return ((string)(this["sp_hom_NFCeConsulta"]));
            }
            set {
                this["sp_hom_NFCeConsulta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.sp.gov.br/ws/recepcaoevento.asmx ")]
        public string sp_hom_NFCeRecepcaoEvento {
            get {
                return ((string)(this["sp_hom_NFCeRecepcaoEvento"]));
            }
            set {
                this["sp_hom_NFCeRecepcaoEvento"] = value;
            }
        }
    }
}
